BEGIN;

ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS can_manage_tasks BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE employees
  ADD COLUMN IF NOT EXISTS can_receive_tasks BOOLEAN NOT NULL DEFAULT FALSE;

COMMIT;
